### ISSUE TITLE
bad html

### ISSUE THREAD

**Issue by FabioZTessitore** [MarioDomenicoDM/MyWebSite#1]
non so dove hai preso le info per fare le pagine così, ma non va per niente bene.
Per cominciare, togli background da body

**Comment by MarioDomenicoDM** [comment]
Perché non va bene ?

**Comment by FabioZTessitore** [comment]
Si faceva così 20 anni fa. Oggi esistono tecniche migliori perché bisogna
gestire anche smartphone e tutto il resto

Il 11 feb 2017 10:58 AM, "MarioDomenicoDM" <notifications@github.com> ha
scritto:

**Comment by MarioDomenicoDM** [comment]
Prof io ho fatto come sta scritto sopra la guida

**Comment by FabioZTessitore** [comment]
Dove? Manda il link

Il 11 feb 2017 11:05 AM, "MarioDomenicoDM" <notifications@github.com> ha
scritto:

**Comment by MarioDomenicoDM** [comment]
http://htmldog.com/guides/html/beginner/tags/

**Comment by FabioZTessitore** [comment]
Cominciamo con il background. Dove lo hai letto? Non c'è

Il 11 feb 2017 1:38 PM, "MarioDomenicoDM" <notifications@github.com> ha
scritto:

**Comment by MarioDomenicoDM** [comment]
Conoscenze personali, l'ha spiegato il prof l'anno scorso

**Comment by FabioZTessitore** [comment]
Appunto resetta

Il 11 feb 2017 5:42 PM, "MarioDomenicoDM" <notifications@github.com> ha
scritto:

**Comment by MarioDomenicoDM** [comment]
Va bene

**Comment by MarioDomenicoDM** [comment]
Quindi tolgo anche i center ?

**Comment by FabioZTessitore** [comment]
Bravo

Il 11 feb 2017 6:07 PM, "MarioDomenicoDM" <notifications@github.com> ha
scritto:

**Comment by MarioDomenicoDM** [comment]
Ora va bene?

**Comment by FabioZTessitore** [comment]
Molto meglio. Ora strong ed em, puoi usarli, ma servono per mettere in evidenza parole o brevi frasi nel testo

**Comment by MarioDomenicoDM** [comment]
Ho lasciato solo quelli fondamentali, si deve correggere altro ?

**Comment by FabioZTessitore** [comment]
ho messo qualche commento, non hai le idee molto chiare

**Comment by MarioDomenicoDM** [comment]
Ho tolto un po di cose

**Comment by FabioZTessitore** [comment]
ho messo altri suggerimenti in ricette

**Comment by MarioDomenicoDM** [comment]
Forse ora va bene

**Comment by FabioZTessitore** [comment]
ricetta ok
