### ISSUE TITLE
login

### ISSUE THREAD

**Issue by FabioZTessitore** [MarioDomenicoDM/MyWebSite#3]

**Comment by FabioZTessitore** [comment]
Manca il tag form

Mancano value nelle option e nelle radio

**Comment by FabioZTessitore** [comment]
Controlla head

**Comment by MarioDomenicoDM** [comment]
Cosa ci devo passare dentro form?
<form action="????" method="????">

**Comment by FabioZTessitore** [comment]
niente per ora, ma ci vuole

**Comment by MarioDomenicoDM** [comment]
Ah va bene!

**Comment by FabioZTessitore** [comment]
Textarea non merita un nome?

**Comment by FabioZTessitore** [comment]
avevo detto un nome

**Comment by FabioZTessitore** [comment]
Niente da fare. Gli altri elementi del form hanno l'attributo name (giusto, serve). Perche il commento no?

**Comment by FabioZTessitore** [comment]
Giusto per informazione, nel caso della textarea non è invece necessario l'attributo value. Ok andiamo avanti
